### ISSUE TITLE
Broken as per Aug 2015

### ISSUE THREAD

**Issue by p1nkyy** [rockihack/FB-OldChatSidebar#1]
Don't really know when it started broken (since I don't use FB Chat too often), but someone mentioned it in the Greasyfork page, checked it and it's true. FF 40.0.2, GM 3.3

**Comment by rockihack** [comment]
I do not use FB anymore... However I fixed the old chat sidebar and it should work again.
Please test it yourself and please confirm that it works for you.

**Comment by p1nkyy** [comment]
Thanks. Works fine now, but the Chat menu is kinda obscured by something... i don't know... is it because I toggle the taskbar in my Windows?
Here's a screenshot:
http://puu.sh/jKdeh/3e8adb985b.png

**Comment by rockihack** [comment]
If no friends are online the chat menu is cut off.
It's a bug, but I don't have any time to fix it right now.
